### ISSUE TITLE
How to extract file from ftp-data?

### ISSUE THREAD

**Issue by chunyunzhe** [snort3/snort3#123]
In the fact, I have extracted file from ftp-data! But it is lace of last frame, the result is that the file's format is broken. Have you ever seen?

**Comment by InverseRE** [comment]
As I understand Snort, its main goal is to examine data for presence of known signatures. But not to extract data for further processing.

Currently, there is no mechanism implemented to extract pure data streams from network flows. Mainly, because this will not support the goal. Also, Snort works in block-mode which is not that friendly with data streams.
