### ISSUE TITLE
Libdaq undefined symbol 

### ISSUE THREAD

**Issue by DigiAngel** [snort3/snort3#145]
Daq was configured with:
~~~
./configure --prefix=/opt/snort3/libdaq
~~~
Run line:
~~~
sudo /opt/snort3/bin/snort -c /opt/snort3/etc/snort/snort.lua --daq-dir /opt/snort3/libdaq/lib/
~~~

result
~~~
/opt/snort3/libdaq/lib//libdaq.so: dlsym: /opt/snort3/libdaq/lib/libdaq.so.3: undefined symbol: DAQ_MODULE_DATA
~~~
Thank you.

**Comment by Xiche** [comment]
This is the expected behavior since you pointed it at the directory with the library itself in it (rather than the direct with just the DAQ modules in it).  It will try to load any .so files it finds recursively in the paths specified and anything that isn't actually a DAQ module it will complain about and then go on with life.  You probably meant to give it --daq-dir /opt/snort3/libdaq/lib/**daq**/.
