### ISSUE TITLE
Undefined Variable Errors

### ISSUE THREAD

**Issue by mandraid** [snort3/snort3#147]
I ran my snort instance as follows: snort -c /usr/local/etc/snort/snort.lua -R /usr/local/etc/snort/rules/snort.rules -i enp3s0 -s 65535 -k none -l /var/log/snort/
I get these errors:
```
Loading rule args:
Loading /usr/local/etc/snort/rules/snort.rules:
ERROR: /usr/local/etc/snort/rules/snort.rules:7 Undefined variable in the string: $HOME_NET.
ERROR: /usr/local/etc/snort/rules/snort.rules:8 Undefined variable in the string: $EXTERNAL_NET.
ERROR: /usr/local/etc/snort/rules/snort.rules:8 undefined variable in the string: $HOME_NET.
ERROR: /usr/local/etc/snort/rules/snort.rules:9 Undefined variable in the string: $HOME_NET.
ERROR: /usr/local/etc/snort/rules/snort.rules:9 undefined variable in the string: $EXTERNAL_NET.
FATAL: /usr/local/etc/snort/rules/snort.rules:9 ***PortVar Lookup failed on '$HTTP_PORTS'.
Fatal Error, Quitting..
```

Yet, in snort.lua, I have these defined, example: 
HOME_NET = '192.168.2.1/24'  
EXTERNAL_NET = 'any'
In my rules file, line 7:
alert tcp $HOME_NET any -> any 3689 ( msg:"APP-DETECT Apple iTunes client request for server info"; flow:to_server,established; content:"/server-info"; flowbits:set,itunes.serverinfo.request; flowbits:noalert; metadata:policy max-detect-ips alert; service:http; reference:url,www.apple.com/itunes/; classtype:misc-activity; sid:13898; rev:10; )
I am running Snort Version 3.0.3 (Build 5) on Ubuntu 20, and am using Pulledpork.  
snort -c /usr/local/etc/snort/snort.lua returns "Snort successfully validated the configuration (with 0 warnings)."

**Comment by matirko** [comment]
Hi, 

This issue tracker is meant for bug reports and feature enhancement requests. For general questions and discussions about Snort usage, please use the Snort-Users mailing list. For discussion about Snort code development, use the Snort-Devel mailing list. Information about the mailing lists can be found here: https://snort.org/community#mailing_lists.

With that being said, variables for IPS have been changed as of commit 75ec38edbfe6. Rather than specifying all variables in variables = {} for IPS, it is broken up into multiple subcategories (variables.nets, variables.ports, etc) now.

In your scenario, the following (or similar) should provide a resolution to your issue.

```lua
ips =
{
    rules = <your rule path here>,
    variables =
    {
        nets =
        {
            EXTERNAL_NET = EXTERNAL_NET,
            HOME_NET = HOME_NET
        },
        ports =
        {
            HTTP_PORTS = HTTP_PORTS
        }
    }
}
```

Alternatively, you could put the definitions here directly
```lua
ips = 
{
    variables =
    {
        nets = {
            HOME_NET = '192.168.2.1/24',
            EXTERNAL_NET = 'any'
        },
        ports =
        {
            HTTP_PORTS = <your ports>
        }
    }
}
```
Thank you for reaching out.
