### ISSUE TITLE
Questions about the snort3 community

### ISSUE THREAD

**Issue by Jianlin-lv** [snort3/snort3#150]
hi, I have been following the snort3 project recently and encountered a few confusions. I hope to find answers here;
1. Is official snort3 maintained on github (https://github.com/snort3/snort3)?
2. I checked the recent Commits information, for example
**‘Merge pull request #2612 in SNORT/snort3 from ~BRASTULT/snort3:byte_math_cursor_fix to master’**
I did not find **PR#2612** on Github, and I cannot fully understand the meaning of commit msg?

3. In addition, Could you introduce the CI/CD status of snort3? I did not find them on github.

**Comment by Xiche** [comment]
Snort 3 is *mirrored* to GitHub, but not maintained/developed here.  That's really the answer to all three of your questions.

**Comment by Xiche** [comment]
Additionally, we have an internal CI/CD process and the biweekly mirroring to GitHub always occurs with a known "good" codebase.

**Comment by Jianlin-lv** [comment]
So, an internal repo responsible for maintaining/developed snort3, which is invisible to the outside, right?

**Comment by Xiche** [comment]
> So, an internal repo responsible for maintaining/developed snort3, which is invisible to the outside, right?

Correct, although all of the commits that get merged are mirrored, so that part doesn't stay invisible.  The Cisco-internal development (bug tracking, PRs, CI, etc.) is not directly visible.  We still use the issue tracker here to track publicly reported issues and will accept pull requests from GitHub, although they will be pulled in through our internal process rather than directly merged on GitHub.

**Comment by Jianlin-lv** [comment]
Thanks for your patience. I`m investigating the status of snort3 on Arm64 recently. So far I have verified the functions of OpenAppID and Registered ruleset on the Arm64 platform, and they all work very well.

One question that I am very concerned about is whether your team only focuses on the x86 platform during the development of snort3? Or is it also considering the support of the arm64 platform?

**Comment by Xiche** [comment]
We are definitely focused on x86 just because it's what we're all developing on and, for the most part, what Snort is running on at the moment.  We try not to preclude other architectures (we're generally high enough level that it mostly doesn't matter) and will periodically at least make sure it still builds on them, but we're not actively developing *for* Arm/Arm64.  We've had engagements in the past where we worked on certain small enhancements for Arm64 (the high-performance stopwatch/clock support is an example).  However, there are still potentially areas of concern for you like our growing reliance on Hyperscan (still optional), which currently doesn't support Arm.

**Comment by yangxile** [comment]
So far, there is Arm sponsored hyperscan implementation in progress at https://github.com/VectorCamp/hyperscan, you can also find some other existing implementations on Arm platform as below:
https://github.com/MarvellEmbeddedProcessors/hyperscan
https://github.com/kunpengcompute/hyperscan
