### ISSUE TITLE
Issue in installl 

### ISSUE THREAD

**Issue by TomaszMyszak** [snort3/snort3#207]
Hello,

when I determine in terminal this line:

./configure_cmake.sh --prefix=$my_path
I have ansewer about issue: 
"CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find DAQ (missing: DAQ_LIBRARIES DAQ_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindDAQ.cmake:34 (find_package_handle_standard_args)
  cmake/include_libraries.cmake:4 (find_package)
  CMakeLists.txt:27 (include)

-- Configuring incomplete, errors occurred!
See also "/home/tomek/snort-source-files/snort3/build/CMakeFiles/CMakeOutput.log".
See also "/home/tomek/snort-source-files/snort3/build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop."

enyone can help me?

**Comment by Normandez** [comment]
Hello,

Thank you for your question.

Snort has a dependency on the libDAQ: https://github.com/snort3/libdaq
You need to have it installed or built from the sources in order to build and run the Snort.
If the libDAQ is not installed into standard path (/usr/local/lib, /usr/lib), use configure_cmake.sh with `--with-daq-libraries=DIR --with-daq-includes=DIR` options to specify the paths to it.
Alternative to using configuration options can be exporting path to libDAQ to PATH, LD_LIBRARY_PATH environment variables.

Also, take a look at the list of [Snort3 dependencies](https://github.com/snort3/snort3#dependencies).

**Comment by snortadmin** [comment]
Also check your PKG_CONFIG_PATH. See the user manual under Tutorial / Building.

________________________________
