### ISSUE TITLE
how to disable inspector modbus

### ISSUE THREAD

**Issue by shirley04** [snort3/snort3#244]
How to disable inspector modbus?  Since CVE-2022-20685 flaw in the Modbus preprocessor of the Snort detection engine could trigger a DoS condition and make it ineffective against malicious traffic.

**Comment by snortadmin** [comment]
You could just update since that was fixed a while back. You should frequently update in any case.

To disable it, just comment out all the lines in snort.lua with modbus by putting -- (double hyphen) at the start of the line.

Also, this is for development issues, not user issues. Use the snort-users mailer for future config and related stuff.
