### ISSUE TITLE
Snort NFQ module not forwarding traffic

### ISSUE THREAD

**Issue by Snorty101** [snort3/snort3#248]
Hi!
I cant´t get snort to bridge the interfaces with the following daq configuration:

daq =
{
    inputs = { '0' },
    modules =
    {
        {
            name = 'nfq',
            mode = 'inline'
        }
    }
}

Running snort with:  snort -c snort.lua  --daq-dir /usr/local/lib/daq --daq nfq --daq-mode inline --daq-var queue=0 -Q

and

iptables -A FORWARD -j NFQUEUE
sysctl net.ipv4.ip_forward=1

Interfaces configured without or static ip, same result..

I start snort first and then apply iptables and ipforwarding.

No connetion.. any suggestions??

**Comment by Xiche** [comment]
Important terminology thing - the NFQ DAQ module is not forwarding traffic in this scenario, it is just marking the packet as ACCEPT or DROP via netlink (except in the REPLACE verdict case, where it will actually send the new packet data back).

Anyway, please make sure the system will function correctly without Snort in the picture by creating the iptables rule with the --queue-bypass and see that traffic is being properly routed.  --daq-var queue=0 does not do anything, please consult the README in the NFQ DAQ module directory for proper usage information.

This tracker is meant for code issues rather than configuration help.  Please use the Snort mailing lists or Discord to ask for configuration help.  Reopen this issue if you can narrow the problem down to a Snort code issue.
