### ISSUE TITLE
Confirmation of correct config setup for IPS

### ISSUE THREAD

**Issue by graysky2** [snort3/snort3#277]
Can someone confirm that I have snort correctly configured to trigger drops?  It is not obvious to me from the log that the packets were dropped or just logged.  I am running snort 3.1.47.0 on OpenWrt like this:
```
/usr/bin/snort -q --daq-dir /usr/lib/daq/ -i eth0 -c /etc/snort/snort.lua -A alert_fast -l /mnt/mmcblk0p3
```
Here is what I'm seeing in `/mnt/mmcblk0p3/alert_fast.txt`
```
11/29-06:52:28.161148 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:59670
11/29-06:52:40.623010 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:57574
11/29-06:52:42.773442 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:60736
11/29-06:52:42.781060 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:62996
11/29-06:53:06.052663 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.0.0.1:53 -> 10.9.1.201:60979
11/29-06:53:25.657182 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.0.0.1:53 -> 10.9.1.201:59517
11/29-06:53:26.738805 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.0.0.1:53 -> 10.9.1.201:55508
11/29-06:53:27.054148 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.0.0.1:53 -> 10.9.1.201:56710
11/29-06:53:28.110628 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.0.0.1:53 -> 10.9.1.201:51132
11/29-06:54:21.043768 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:64747
11/29-06:54:44.405450 [**] [1:254:16] "PROTOCOL-DNS SPOOF query response with TTL of 1 min. and no authority" [**] [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 1.1.1.1:53 -> 10.9.1.201:61806
```

I attached my `/etc/snort/snort.lua` and `/etc/snort/snort_defaults.lua` for reference.  Thanks in advance for any feedback/suggestions.

[snort.lua](https://github.com/snort3/snort3/files/10113281/snort.lua.txt)
[snort_defaults.lua](https://github.com/snort3/snort3/files/10113282/snort_defaults.lua.txt)

**Comment by matirko** [comment]
Hi, in general, we use this Issues page for issues with the Snort3 codebase. For config-related questions, we usually recommend reaching out to [our email lists ](https://www.snort.org/community#mailing_listsl) or [our discord](https://blog.snort.org/2021/07/join-snort-on-discord.html)

With that being said, I checked out those rules in the registered ruleset, and they (the DNS rules) appear to be _alert_ rules rather than drop rules, so I believe it's just alerting on those packets. This should also be visible in the Snort exit stats, showing an alert rather than a drop/block verdict.

**Comment by graysky2** [comment]
@matirko - thank you for the reply.  I will take future newbie questions else where.  To finish this guys, building on your observation about alert vs drop, can you advise me how to adjust these to be drop?  I understood the `mode = inline,` statement in the `ips =` section to change the behavior of alter vs drop.  I must be misunderstanding.  Thanks!

**Comment by matirko** [comment]
> @matirko - thank you for the reply. I will take future newbie questions else where. To finish this guys, building on your observation about alert vs drop, can you advise me how to adjust these to be drop? I understood the `mode = inline,` statement in the `ips =` section to change the behavior of alter vs drop. I must be misunderstanding. Thanks!

No worries. The rules in Snort always start with an action (alert | block | drop | file_id | log | pass | react | reject | rewrite ). Even if Snort is configured inline, this simply gives it the ability to directly modify the flows that it sees - it requires a rule to tell it to do so, however. 

In this case, those rule matches you shared seem to be alert rules, which will deliver an alert through whichever alert module you have enabled (e.x, `alert_csv`, `alert_json`, `alert_syslog`, or others). This shouldn't affect the traffic however. If you want to drop or block this, switch out the action keyword with `drop` or `block` rather than alert. `drop` will drop matching packets, while `block` will continue blocking for the remainder of that flow. 

These rules exist in `snort3-protocol-dns.rules` from the rules snapshot and should be able to be edited from there.

**Comment by graysky2** [comment]
So the rules tarball seem to be initially configured for `alert` actions only if I understand you correctly.  That must imply that users need to process each of the `.rules` like this for example:
```
for i in *.rules; do sed -i s'/^alert/drop/' "$i"; done
```

Am I correct?

**Comment by InverseRE** [comment]
> I am now seeing `would_drop` for matches rather than `alert` so that is progress!

I guess, Snort is not in the inline mode. You might want to add '-Q' config option to the command line.

**Comment by graysky2** [comment]
Thanks, I got this working.  See: https://github.com/openwrt/packages/pull/19989

**Comment by InverseRE** [comment]
> So the rules tarball seem to be initially configured for `alert` actions only if I understand you correctly. That must imply that users need to process each of the `.rules`

Also, you can take advantage of the ips.states option if you need just a subset of rules. The following lines in the configuration file will turn the rule to drop packets:
 ```
ips.states =
[[
    drop ( gid:1;   sid: 254;   enable:yes; )
]]
```

**Comment by graysky2** [comment]
Thanks @InverseRE, great suggestion

**Comment by huyunceng** [comment]
thanks
| |
胡云层
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/4/2023 15:42 |
| To | ***@***.******@***.***> |
| Cc | ***@***.******@***.***> ,
***@***.******@***.***> |
| Subject | Re: [snort3/snort3] Confirmation of correct config setup for IPS (Issue #277) |


hello
| |
胡云层
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/2/2023 18:17 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [snort3/snort3] Confirmation of correct config setup for IPS (Issue #277) |

Thanks @InverseRE, great suggestion

**Comment by huyunceng** [comment]
test
hello
| |
胡云层
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 5/2/2023 18:17 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [snort3/snort3] Confirmation of correct config setup for IPS (Issue #277) |

Thanks @InverseRE, great suggestion

**Comment by huyunceng** [comment]
thanks


| |
胡云层
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/6/2022 01:49 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [snort3/snort3] Confirmation of correct config setup for IPS (Issue #277) |

I am now seeing would_drop for matches rather than alert so that is progress!

I guess, Snort is not in the inline mode. You might want to add '-Q' config option to the command line.
