### ISSUE TITLE
Build failure on macOS Ventura

### ISSUE THREAD

**Issue by p-linnane** [snort3/snort3#297]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While attempting to package snort v3.1.58.0 we are running into errors building on macOS Ventura. We are using build patches submitted by one of our maintainers in https://github.com/snort3/snort3/pull/286. Any advice on why our build is failiing specifically on Ventura would be appreciated.

Relates to https://github.com/Homebrew/homebrew-core/pull/126679.

**Comment by Xiche** [comment]
This isn't a Snort issue.

It looks like the `patch` utility on your Ventura build machine has gotten pickier in its behavior and is rejecting the not-quite-aligned patch due to other changes in the files being touched.

On my Linux box:
```
$ patch -g 0 -f -p1 -i 2b498993a47c728c3e273b440266eb40e5aa56c6.patch
patching file src/helpers/process.cc
patching file src/memory/memory_cap.cc
Hunk #2 succeeded at 307 with fuzz 2 (offset 6 lines).

$ patch --version
GNU patch 2.7.6
```
Versus on my Ventura box:
```
$ patch -g 0 -f -p1 -i 2b498993a47c728c3e273b440266eb40e5aa56c6.patch 
patching file 'src/helpers/process.cc'
patching file 'src/memory/memory_cap.cc'
1 out of 2 hunks failed--saving rejects to 'src/memory/memory_cap.cc.rej'

$ patch --version
patch 2.0-12u11-Apple
```
This is normally controlled by the fuzz factor (-F flag for `patch`).

Regardless, rebasing the patch should solve your issue so that it applies cleanly.

**Comment by chenrui333** [comment]
> This isn't a Snort issue.

@Xiche this is because the valid patch never got merged, so in some sense, it is indeed a snort issue. Any timeline of merging the patch?

**Comment by InverseRE** [comment]
>  the valid patch never got merged, so in some sense, it is indeed a snort issue. Any timeline of merging the patch?

On a local OSX I made a symlink, that fixed my build:
`sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc/malloc.h /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/malloc.h`

Also I believe, there are other ways to provide a correct path to header files, avoiding patching the source code.

The patch suggested seems incomplete to me:
1. src/memory/memory_cap.cc doesn't use any function from malloc.h, the including file could be simply removed.
2. as for src/helpers/process.cc , do you get HAVE_MALLOC_TRIM defined? My CMake doesn't defined that, so that file is not a problemer. No need to fix until proved otherwise.
