### ISSUE TITLE
Linking CXX executable error snort

### ISSUE THREAD

**Issue by Ogbenigoke** [snort3/snort3#322]
This is the error I'm coming across during installation on Ubuntu v22.04. Kindly advice on what to do
![image](https://github.com/snort3/snort3/assets/105822438/d76a04bb-b5db-46c5-9d17-03f37bbd2633)

**Comment by ansrb** [comment]
Linker being killed with signal 9 isn't typical to be caused by the application being linked.
This most likely indicates that your machine ran out of available RAM. Could this be the case?
If it is you could try to link snort with more available RAM, either lowering usage by other processes, or provide more RAM to the machine (if possible at all).
If you are running make in multiple threads (`-j` flag), maybe running it with only one would help. Also, I read that LLVM's lld linker achieved lower memory usage, but can't confirm.

**Comment by Ogbenigoke** [comment]
Increasing the RAM of the VM works, thank you.
