### ISSUE TITLE
where are stored the pcap files by default ?

### ISSUE THREAD

**Issue by aragon5956** [snort3/snort3#343]
hello , where are stored pcap files by default with this command : "[Unit]
Description=Snort3 NIDS Daemon
After=syslog.target network.target
[Service]
Type=simple
ExecStart=/usr/local/bin/snort -c /usr/local/etc/snort/snort.lua -s 65535 \
-k none -l /var/log/snort -D -u snort -g snort -i ens37 -m 0x1b --create-pidfile \
--plugin-path=/home/alexandre/téléchargements/snort3-community-rules/snort3-community-rules.rules
[Install]
WantedBy=multi-user.target"

 considering the -r option is linking with pcap files

Cordially

**Comment by matirko** [comment]
`-r` specifies pcap readback mode. It is used for reading from a packet capture file.

For _writing_ to a pcap, I would recommend you look into our output module for this use case, `log_pcap`, which can be found here: https://github.com/snort3/snort3/blob/master/src/loggers/log_pcap.cc

For config issues/questions like this, rather than bugs, we tend to refer people to our [email lists](https://www.snort.org/community), or [our discord](https://blog.snort.org/2021/07/join-snort-on-discord.html), so if you have follow up questions on this, please don't hesitate to ask on one of those platforms.
