### ISSUE TITLE
PCRE unsupported configuration : both relative & uri options specified

### ISSUE THREAD

**Issue by ralax123** [snort3/snort3#377]
my snort version is :Version 2.9.17.1 GRE (Build 1013)

the snort rule is :
alert tcp $EXTERNAL_NET any -> $HOME_NET any (msg:"ETPRO TROJAN DBatLoader Payload Response via OneDrive"; flow:to_client; content:"200"; http_stat_code; content:"Content-Location|3a 20|"; http_header; content:".dm.files.1drv.com/"; http_header; within:40; fast_pattern; content:"Content-Disposition|3a 20|attachment|3b 20|filename=|22|"; http_header; pcre:"/^[A-Z][a-z]{30}\x22\x0d\x0a/HR";  content:"application/octet-stream"; depth:24; isdataat:!1,relative; classtype:trojan-activity; priority:1; sid:4320003; rev:2; metadata:subtype 1001, altertype None;)

but when I test snort rules config by use command:
 snort -c /etc/snort/snort.conf  -T

it will console:
ERROR: /etc/snort/rules/Others.rules(529): PCRE unsupported configuration : both relative & uri options specified
Fatal Error, Quitting..
![Uploading image.png…]()

what is the probrom?    please help me !!!

**Comment by matirko** [comment]
Hi, this issues page is intended exclusively for Snort3 bugs. For configuration issues (with both Snort 2 and Snort3) reach out to one of our [mailing lists](https://www.snort.org/community#mailing_lists).

With that being said, the issue here is that you are using both a relative (`R`) modifier and an HTTP modifier. Our [user manual](http://manual-snort-org.s3-website-us-east-1.amazonaws.com/node163.html) goes over this pretty well, but the important bit is:
>The modifiers R (relative) and B (rawbytes) are not allowed with any of the HTTP modifiers such as U, I, P, H, D, M, C, K, S and Y.

**Comment by snortadmin** [comment]
FYI - Snort 3 does not have this limitation.
